### PR TITLE
chore(sponsorship) Add 2022 prospectus PDFs

### PR DESCRIPTION
**Pull request by Cueball**
chore(sponsorship) Update sponsorship text+PDFs

### CODE REVIEW

**Review by mathewdbutton — APPROVED** [review]
Extra points for light and dark version!

LGTM! Well done @Cueball

**Comment by Cueball** [comment]
OK thanks @mathewdbutton - merging. What could go wrong? 😂

**Review by pat — APPROVED** [review]

**Comment by pat** [comment]
We don't have auto-deploy set up for this repo (I re-realised yesterday). I'll deploy it manually in a moment.

**Comment by pat** [comment]
https://ruby.org.au/sponsorship 🚢

**Pull request merged**
