### PR TITLE
Add two new sponsors

### PR DESCRIPTION
**Pull request by RachelleOnRails**
Add reinteractive as an Emerald sponsor, and Oneflare as an Opal sponsor.

### CODE REVIEW

**Comment by cpalmerbright** [comment]
* the opal styling in sponsorship.scss has a block display style that is making the logo sit too close to the header - getting rid of that line works
* there is no reinteractive md file under views/pages/sponsors so clicking the image gives an error

**Comment by cpalmerbright** [comment]
just made those changes - created the markdown file and removed the weird styling on the oneflare logo. Just add whatever blurb reinteractive wants on their individual page :)

**Comment by quintrino** [comment]
Whoops, sorry @radar I clicked the wrong button!

**Comment by RachelleOnRails** [comment]
Duh! OK, could you review again please @cpalmerbright or @antulik?

**Pull request merged**
