### PR TITLE
Task/upgrade to rails 8

### PR DESCRIPTION
**Pull request by leesheppard**
Upgrade from 7.2 to 8.0

### CODE REVIEW

**Comment by gamesover** [comment]
After upgrading to Rails 8, Webpacker is encountering issues in the development environment.

```
ubuntu@code-server:~/projects/ruby_au$ yarn start
yarn run v1.22.22
$ NODE_OPTIONS=--openssl-legacy-provider bin/webpack-dev-server
[webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'https'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, ipc?, liveReload?, onListening?, open?, port?, proxy?, server?, app?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

remove `https: false` from `config/webpacker.yml` does not help.

I think we need to implement https://github.com/rubyaustralia/ruby_au/issues/204 ticket.

For now, we can run `rails assets:precompile` in development to get latest frontend assets

**Comment by leesheppard** [comment]
Currently working in a branch to replace Webpacker at present with Vite.

**Comment by leesheppard** [comment]
@gamesover I've now got a [PR](https://github.com/rubyaustralia/ruby_au/pull/268) in place for Vite to take over

**Comment by gamesover** [comment]
Fantastic work, @leesheppard!  
Thank you so much for your swift action.  

A bit off-topic – I know this project doesn’t require PDF generation, but I came across this [article](https://www.stefanwienert.de/blog/2022/07/11/migrating-from-webpacker-to-vite-rails/) discussing the migration from Webpacker to Vite.  

> One major drawback of Vite is that wkhtmltopdf can no longer generate styled PDFs. While this isn’t an issue for this project, future projects requiring styled PDFs would need to migrate to Puppeteer or similar alternatives ([see GitHub discussion](https://github.com/ElMassimo/vite_ruby/discussions/201)).  

Wicked_PDF and wkhtmltopdf are widely used in many Ruby on Rails projects. If Vite doesn’t support them, it could become a significant challenge.  

In such cases, do you know of any workarounds or alternative libraries that support wkhtmltopdf? Or would you recommend alternatives to Vite that maintain compatibility with wkhtmltopdf?  

Appreciate any insights you might have!

**Comment by gamesover** [comment]
> @gamesover There’s no fundamental incompatibility between Vite and WickedPDF, only the need to configure asset references so that the PDF generator can do its job correctly. It comes down to how you reference static assets so that wkhtmltopdf can properly find them. Ensuring that your PDF-generating views (or layouts) use either:
> 
> * Fully compiled (production) paths for CSS/JS/images
> * A separate minimal set of inline or absolute-file paths
> 
> As mentioned above, the common workaround is to ensure your PDF views reference compiled assets rather than the dev server. In other words, you generate your PDF against the production-bundled assets in `public/vite/assets`

Thanks for your advice. If so, `Vite` is a perfect solution to me.

**Pull request merged**
